#! /usr/bin/python
import os
import select
import sys
import time
import os
import termios

def kbhit():
    fd = sys.stdin.fileno()
    r = select.select([sys.stdin],[],[],0.01)
    rcode = ''
    if len(r[0]) >0:
        rcode  = sys.stdin.read(1)
    return rcode

fd = sys.stdin.fileno()
old_settings = termios.tcgetattr(fd)
new_settings = old_settings
#new_settings[3] = new_settings[3] & ~termios.ISIG
new_settings[3] = new_settings[3] & ~termios.ICANON
new_settings[3] = new_settings[3] & ~termios.ECHONL
termios.tcsetattr(fd,termios.TCSAFLUSH,new_settings)

#save the resault
output = open('result', 'w')
output.write("down rate(kbit/s)    up rate(kbit/s)")
while True:
    cmd="tshark -q -i eth2 -a duration:1 -z  conv,udp,ip.addr==192.168.0.108 > temp"
    c = kbhit()
    if len(c) !=0 :
        print '%s'%(c)
        if c=='q':
            break
        else:
            cmd="tshark -q -i eth2 -a duration:"+c+" -z  conv,udp,ip.addr==192.168.0.108 > temp"
    #capture packet
    os.system(cmd)
    os.system("cat ./temp | grep \"<->\" >temp1")
    os.system("clear")
    print "****code rate real time statistics****"
    print "ipaddres                                      < rate(kbit/s)    > rate(kbit/s)"
    f = open("temp1")       
    line = f.readline()
    output = open('result', 'a') 
    while line:
        line= line.split()
        if float(line[10])==0:
            line=f.readline()
            continue 
        down=float(line[4])/float(line[10])
        up=float(line[6])/float(line[10])
        output.write("\n"+str('%0.2f' %(down*8/1000))+'            '+str('%0.2f' %(up*8/1000)))    
        print line[0]+line[1]+line[2]+"    ",'%0.2f' %(down*8/1000),'            ','%0.2f' %(up*8/1000)
        line=f.readline()
    f.close()
    output.close()
    #break
    
    

